"""Initial migration

Revision ID: a351abd0c853
Revises: 
Create Date: 2021-01-23 17:16:11.605072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a351abd0c853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_exam_genres_name'))
    )
    op.create_table('exam_posters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('md5_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_posters')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_exam_posters_md5_hash'))
    )
    op.create_table('exam_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_roles'))
    )
    op.create_table('exam_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('production_year', mysql.YEAR(), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('producer', sa.String(length=128), nullable=False),
    sa.Column('scenarist', sa.String(length=128), nullable=False),
    sa.Column('actors', sa.String(length=256), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.Column('poster_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['exam_posters.id'], name=op.f('fk_exam_movies_poster_id_exam_posters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_movies'))
    )
    op.create_table('exam_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['exam_roles.id'], name=op.f('fk_exam_users_role_id_exam_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_users')),
    sa.UniqueConstraint('login', name=op.f('uq_exam_users_login'))
    )
    op.create_table('exam_genre_movie',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['exam_genres.id'], name=op.f('fk_exam_genre_movie_genre_id_exam_genres')),
    sa.ForeignKeyConstraint(['movie_id'], ['exam_movies.id'], name=op.f('fk_exam_genre_movie_movie_id_exam_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('pk_exam_genre_movie'))
    )
    op.create_table('exam_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['exam_movies.id'], name=op.f('fk_exam_reviews_movie_id_exam_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['exam_users.id'], name=op.f('fk_exam_reviews_user_id_exam_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_reviews')
    op.drop_table('exam_genre_movie')
    op.drop_table('exam_users')
    op.drop_table('exam_movies')
    op.drop_table('exam_roles')
    op.drop_table('exam_posters')
    op.drop_table('exam_genres')
    # ### end Alembic commands ###
