"""add status

Revision ID: bb538c4b0d97
Revises: a351abd0c853
Create Date: 2021-01-26 21:41:15.396827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb538c4b0d97'
down_revision = 'a351abd0c853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_statuses',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_exam_statuses'))
    )
    op.add_column('exam_reviews', sa.Column('status', sa.String(length=128), nullable=False))
    op.create_foreign_key(op.f('fk_exam_reviews_status_exam_statuses'), 'exam_reviews', 'exam_statuses', ['status'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_exam_reviews_status_exam_statuses'), 'exam_reviews', type_='foreignkey')
    op.drop_column('exam_reviews', 'status')
    op.drop_table('exam_statuses')
    # ### end Alembic commands ###
